image: alpine/edge
secrets:
  - ca99d209-296a-41b7-9eda-454250e4b901
packages:
  - rust
  - cargo
environment:
  REPO: janus
sources:
  - https://git.sr.ht/~ekoeppen/build-scripts
  - https://git.sr.ht/~ekoeppen/janus
  - https://git.sr.ht/~ekoeppen/CoreForth-0
  - https://git.sr.ht/~ekoeppen/p3216
tasks:
  - mirror-to-github: ./build-scripts/github-mirror $REPO
  - build-p3216: |
      cp janus/bin/p3216 p3216/image.bin
      cd p3216
      cargo build --profile release --features preload
  - build-coreforth-p3216: |
      p3216/target/release/p3216 janus/janus.ft -f CoreForth-0/p3216/p3216.ft
artifacts:
  - p3216.bin
