name: Compile

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    environment: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ekoeppen/janus/janus:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_read }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile
        run: |
          gforth janus.ft CoreForth-0/p3216/p3216.ft
          gforth janus.ft CoreForth-0/cortex/boards/thumbulator-m3.ft stc
          gforth janus.ft CoreForth-0/cortex/boards/thumbulator-m3.ft dtc
          gforth janus.ft CoreForth-0/cortex/boards/nucleo-f103rb.ft stc
          gforth janus.ft CoreForth-0/cortex/boards/nucleo-f103rb.ft dtc
      - name: Save CoreForth-0
        uses: actions/upload-artifact@v2
        with:
          name: CoreForth-0
          path: |
            /home/user/janus/*.bin
            /home/user/janus/*.hex
      - name: Test p3216
        run: |
          ./CoreForth-0/tests/test.sh | p3216 p3216.bin
