name: Compile

on: [pull_request, workflow_dispatch]

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile
        run: |
          echo "Compiling p3216 bootstrap binary..."
          gforth janus.ft -f CoreForth-0/p3216/p3216.ft
          echo "Compiling p3216 final binary..."
          p3216 p3216.bin janus.ft -f CoreForth-0/p3216/p3216.ft
          echo "Compiling MSP430G2 Launchpad binary..."
          p3216 p3216.bin janus.ft -f CoreForth-0/msp430/boards/msp-exp430g2.ft
          echo "Compiling MSP430 Emulator binary..."
          p3216 p3216.bin janus.ft -f CoreForth-0/msp430/boards/msp430-emu.ft
          echo "Compiling Thumbulator STC binary..."
          p3216 p3216.bin janus.ft --stc -f CoreForth-0/cortex/boards/thumbulator.ft
          echo "Compiling Thumbulator DTC binary..."
          p3216 p3216.bin janus.ft --dtc -f CoreForth-0/cortex/boards/thumbulator.ft
          echo "Compiling Thumbulator ITC binary..."
          p3216 p3216.bin janus.ft --itc -f CoreForth-0/cortex/boards/thumbulator.ft
          echo "Compiling Thumbulator M3 STC binary..."
          p3216 p3216.bin janus.ft --stc -f CoreForth-0/cortex/boards/thumbulator-m3.ft
          echo "Compiling Thumbulator M3 DTC binary..."
          p3216 p3216.bin janus.ft --dtc -f CoreForth-0/cortex/boards/thumbulator-m3.ft
          echo "Compiling Nucleo F072RB STC binary..."
          p3216 p3216.bin janus.ft --stc -f CoreForth-0/cortex/boards/nucleo-f072rb.ft
          echo "Compiling Nucleo F072RB DTC binary..."
          p3216 p3216.bin janus.ft --dtc -f CoreForth-0/cortex/boards/nucleo-f072rb.ft
          echo "Compiling Nucleo F103RB STC binary..."
          p3216 p3216.bin janus.ft --stc -f CoreForth-0/cortex/boards/nucleo-f103rb.ft
          echo "Compiling Nucleo F103RB DTC binary..."
          p3216 p3216.bin janus.ft --dtc -f CoreForth-0/cortex/boards/nucleo-f103rb.ft
          echo "Compiling Nucleo F303RE STC binary..."
          p3216 p3216.bin janus.ft --stc -f CoreForth-0/cortex/boards/nucleo-f303re.ft
          echo "Compiling Nucleo F303RE DTC binary..."
          p3216 p3216.bin janus.ft --dtc -f CoreForth-0/cortex/boards/nucleo-f303re.ft
          echo "Compilation done."
      - name: Save CoreForth-0
        uses: actions/upload-artifact@v2
        with:
          name: CoreForth-0
          path: |
            CoreForth-0
            *.bin
            *.hex

  test-p3216:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Test
        working-directory: CoreForth-0
        run: |
          p3216 p3216.bin CoreForth-0/tests/test.ft

  test-msp430:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Test
        working-directory: CoreForth-0
        run: |
          sh ./CoreForth-0/tests/test.sh | msp430-emu -r -m 1000 -b msp430-emu-info.bin -m 4000 -b msp430-emu-main.bin -m ffc0 -b msp430-emu-vectors.bin

  test-cortex-m0-stc:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Test
        working-directory: CoreForth-0
        run: |
          sh ./CoreForth-0/tests/test.sh | thumbulator -d thumbulator-stc.bin

  test-cortex-m0-dtc:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Test
        working-directory: CoreForth-0
        run: |
          sh ./CoreForth-0/tests/test.sh | thumbulator -d thumbulator-dtc.bin

  test-cortex-m0-itc:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Test
        working-directory: CoreForth-0
        run: |
          sh ./CoreForth-0/tests/test.sh | thumbulator -d thumbulator-itc.bin

  test-cortex-m3-stc:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Test
        working-directory: CoreForth-0
        run: |
          sh ./CoreForth-0/tests/test.sh | thumbulator -d thumbulator-m3-stc.bin

  test-cortex-m3-dtc:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:1.4.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Test
        working-directory: CoreForth-0
        run: |
          sh ./CoreForth-0/tests/test.sh | thumbulator -d thumbulator-m3-dtc.bin
