name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/user
    container:
      image: docker.pkg.github.com/ekoeppen/gforth-docker/gforth:0.7.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_read }}
    steps:
      - name: Checkout
        run: |
          git clone --recursive https://github.com/${{ github.repository }}.git janus
          cd janus && git reset --hard ${{ github.sha }}
      - name: Compile
        working-directory: /home/user/janus
        run: |
          gforth janus.ft CoreForth-0/p3216/p3216.ft
          gforth janus.ft CoreForth-0/cortex/boards/thumbulator-m3.ft stc
          gforth janus.ft CoreForth-0/cortex/boards/thumbulator-m3.ft dtc
          gforth janus.ft CoreForth-0/cortex/boards/nucleo-f103rb.ft stc
          gforth janus.ft CoreForth-0/cortex/boards/nucleo-f103rb.ft dtc
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CoreForth-0
          path: |
            /home/user/janus/*.bin
            /home/user/janus/*.hex
